import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header/Header";
import Providers from "@/Providers";
import Nav from "@/components/navBar/Nav";
import SearchBox from "@/components/SearchBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Nav />
          <SearchBox />
          {children}
        </Providers>
      </body>
    </html>
  );
}
